<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Resep;

class ResepSeeder extends Seeder
{
    public function run(): void
    {
        $reseps = [

            // ── MAKANAN BERAT (main_filter_id: 1) ─────────────
            [
                'user_id'        => 1,
                'title'          => 'Nasi Goreng Spesial',
                'description'    => 'Nasi goreng rumahan dengan telur dan ayam.',
                'cook_duration'  => '00:20:00',
                'calorie'        => 550,
                'current_star'   => 4.8,
                'views_count'    => 120,
                'thumbnail'      => 'images/reseps/nasi_goreng.jpeg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 2,
                'title'          => 'Mie Goreng Jawa',
                'description'    => 'Mie goreng manis gurih khas Jawa.',
                'cook_duration'  => '00:15:00',
                'calorie'        => 480,
                'current_star'   => 4.6,
                'views_count'    => 95,
                'thumbnail'      => 'images/reseps/mie-goreng-jawa.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 3,
                'title'          => 'Telur Dadar Crispy',
                'description'    => 'Telur dadar renyah dan gurih.',
                'cook_duration'  => '00:10:00',
                'calorie'        => 300,
                'current_star'   => 4.5,
                'views_count'    => 75,
                'thumbnail'      => 'images/reseps/telur-dadar-crispy.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 4,
                'title'          => 'Ayam Kecap Pedas',
                'description'    => 'Ayam manis pedas dengan bumbu kecap.',
                'cook_duration'  => '00:30:00',
                'calorie'        => 620,
                'current_star'   => 4.9,
                'views_count'    => 210,
                'thumbnail'      => 'images/reseps/ayam-kecap-pedas.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 5,
                'title'          => 'Capcay Sayur',
                'description'    => 'Menu sehat dengan berbagai sayuran.',
                'cook_duration'  => '00:25:00',
                'calorie'        => 350,
                'current_star'   => 4.7,
                'views_count'    => 80,
                'thumbnail'      => 'images/reseps/capcay-sayur.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 1,
                'title'          => 'Soto Ayam',
                'description'    => 'Sup ayam kuning khas Indonesia yang segar.',
                'cook_duration'  => '00:45:00',
                'calorie'        => 420,
                'current_star'   => 4.8,
                'views_count'    => 180,
                'thumbnail'      => 'images/reseps/soto_ayam.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 2,
                'title'          => 'Rendang Daging',
                'description'    => 'Daging sapi dimasak dengan santan dan rempah khas Minang.',
                'cook_duration'  => '02:00:00',
                'calorie'        => 780,
                'current_star'   => 5.0,
                'views_count'    => 320,
                'thumbnail'      => 'images/reseps/rendang_daging.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 3,
                'title'          => 'Opor Ayam',
                'description'    => 'Ayam dalam kuah santan kuning yang gurih.',
                'cook_duration'  => '00:50:00',
                'calorie'        => 560,
                'current_star'   => 4.7,
                'views_count'    => 145,
                'thumbnail'      => 'images/reseps/opor_ayam.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 4,
                'title'          => 'Nasi Uduk',
                'description'    => 'Nasi gurih dimasak dengan santan dan rempah.',
                'cook_duration'  => '00:35:00',
                'calorie'        => 490,
                'current_star'   => 4.6,
                'views_count'    => 110,
                'thumbnail'      => 'images/reseps/nasi_uduk.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 5,
                'title'          => 'Gado-gado',
                'description'    => 'Sayuran rebus dengan saus kacang yang khas.',
                'cook_duration'  => '00:30:00',
                'calorie'        => 380,
                'current_star'   => 4.5,
                'views_count'    => 90,
                'thumbnail'      => 'images/reseps/gado_gado.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],

            // ── CAMILAN (main_filter_id: 2) ────────────────────
            [
                'user_id'        => 1,
                'title'          => 'Pisang Goreng Crispy',
                'description'    => 'Pisang goreng renyah dengan tepung berbumbu.',
                'cook_duration'  => '00:15:00',
                'calorie'        => 250,
                'current_star'   => 4.6,
                'views_count'    => 130,
                'thumbnail'      => 'images/reseps/pisang_goreng_crispy.jpg',
                'main_filter_id' => 2,
                'is_published'   => true,
            ],
            [
                'user_id'        => 2,
                'title'          => 'Tahu Crispy',
                'description'    => 'Tahu goreng renyah dengan balutan tepung bumbu.',
                'cook_duration'  => '00:20:00',
                'calorie'        => 200,
                'current_star'   => 4.4,
                'views_count'    => 85,
                'thumbnail'      => 'images/reseps/tahu_crispy.jpg',
                'main_filter_id' => 2,
                'is_published'   => true,
            ],
            [
                'user_id'        => 3,
                'title'          => 'Tempe Mendoan',
                'description'    => 'Tempe goreng tipis dengan bumbu khas Banyumas.',
                'cook_duration'  => '00:15:00',
                'calorie'        => 180,
                'current_star'   => 4.5,
                'views_count'    => 95,
                'thumbnail'      => 'images/reseps/tempe_mendoan.jpg',
                'main_filter_id' => 2,
                'is_published'   => true,
            ],
            [
                'user_id'        => 4,
                'title'          => 'Bakwan Sayur',
                'description'    => 'Gorengan sayuran dengan tepung yang renyah.',
                'cook_duration'  => '00:20:00',
                'calorie'        => 220,
                'current_star'   => 4.3,
                'views_count'    => 70,
                'thumbnail'      => 'images/reseps/bakwan_sayur.jpg',
                'main_filter_id' => 2,
                'is_published'   => true,
            ],
            [
                'user_id'        => 5,
                'title'          => 'Onde-onde',
                'description'    => 'Kue bulat berbalut wijen dengan isian kacang hijau.',
                'cook_duration'  => '00:40:00',
                'calorie'        => 290,
                'current_star'   => 4.7,
                'views_count'    => 115,
                'thumbnail'      => 'images/reseps/onde_onde.jpg',
                'main_filter_id' => 2,
                'is_published'   => true,
            ],

            // ── MINUMAN (main_filter_id: 3) ────────────────────
            [
                'user_id'        => 1,
                'title'          => 'Es Teh Manis',
                'description'    => 'Minuman teh manis dingin yang menyegarkan.',
                'cook_duration'  => '00:05:00',
                'calorie'        => 80,
                'current_star'   => 4.5,
                'views_count'    => 200,
                'thumbnail'      => 'images/reseps/es_teh.jpg',
                'main_filter_id' => 3,
                'is_published'   => true,
            ],
            [
                'user_id'        => 2,
                'title'          => 'Jus Alpukat',
                'description'    => 'Jus alpukat creamy dengan susu dan gula.',
                'cook_duration'  => '00:10:00',
                'calorie'        => 220,
                'current_star'   => 4.8,
                'views_count'    => 160,
                'thumbnail'      => 'images/reseps/jus_alpukat.jpg',
                'main_filter_id' => 3,
                'is_published'   => true,
            ],
            [
                'user_id'        => 3,
                'title'          => 'Es Cincau Hijau',
                'description'    => 'Minuman cincau segar dengan santan dan gula merah.',
                'cook_duration'  => '00:15:00',
                'calorie'        => 150,
                'current_star'   => 4.6,
                'views_count'    => 120,
                'thumbnail'      => 'images/reseps/es_cincau_hijau.jpg',
                'main_filter_id' => 3,
                'is_published'   => true,
            ],

            // ── DESSERT (main_filter_id: 4) ────────────────────
            [
                'user_id'        => 4,
                'title'          => 'Klepon',
                'description'    => 'Kue bola hijau berisi gula merah cair.',
                'cook_duration'  => '00:30:00',
                'calorie'        => 180,
                'current_star'   => 4.8,
                'views_count'    => 140,
                'thumbnail'      => 'images/reseps/klepon.png',
                'main_filter_id' => 4,
                'is_published'   => true,
            ],
            [
                'user_id'        => 5,
                'title'          => 'Bubur Sumsum',
                'description'    => 'Bubur tepung beras dengan kuah gula merah.',
                'cook_duration'  => '00:25:00',
                'calorie'        => 210,
                'current_star'   => 4.7,
                'views_count'    => 100,
                'thumbnail'      => 'images/reseps/bubur_sumsum.jpg',
                'main_filter_id' => 4,
                'is_published'   => true,
            ],
            [
                'user_id'        => 1,
                'title'          => 'Puding Coklat',
                'description'    => 'Puding coklat lembut dengan saus vanilla.',
                'cook_duration'  => '00:20:00',
                'calorie'        => 240,
                'current_star'   => 4.6,
                'views_count'    => 130,
                'thumbnail'      => 'images/reseps/puding_coklat.jpg',
                'main_filter_id' => 4,
                'is_published'   => true,
            ],

            // ── TAMBAHAN MAKANAN BERAT ─────────────────────────
            [
                'user_id'        => 2,
                'title'          => 'Ayam Bakar Bumbu Rujak',
                'description'    => 'Ayam bakar dengan bumbu pedas manis khas.',
                'cook_duration'  => '00:50:00',
                'calorie'        => 590,
                'current_star'   => 4.9,
                'views_count'    => 250,
                'thumbnail'      => 'images/reseps/ayam_bakar_bumbu_rujak.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 3,
                'title'          => 'Ikan Goreng Sambal',
                'description'    => 'Ikan goreng garing disajikan dengan sambal merah.',
                'cook_duration'  => '00:25:00',
                'calorie'        => 410,
                'current_star'   => 4.7,
                'views_count'    => 175,
                'thumbnail'      => 'images/reseps/ikan_goreng_sambal.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 4,
                'title'          => 'Tumis Kangkung',
                'description'    => 'Kangkung tumis dengan bawang dan cabai.',
                'cook_duration'  => '00:10:00',
                'calorie'        => 150,
                'current_star'   => 4.5,
                'views_count'    => 85,
                'thumbnail'      => 'images/reseps/tumis_kangkung.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 5,
                'title'          => 'Sop Buntut',
                'description'    => 'Sup buntut sapi dengan kuah bening yang gurih.',
                'cook_duration'  => '01:30:00',
                'calorie'        => 650,
                'current_star'   => 4.9,
                'views_count'    => 280,
                'thumbnail'      => 'images/reseps/sop_buntut.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 1,
                'title'          => 'Pecel Lele',
                'description'    => 'Lele goreng dengan sambal pecel yang segar.',
                'cook_duration'  => '00:20:00',
                'calorie'        => 380,
                'current_star'   => 4.6,
                'views_count'    => 145,
                'thumbnail'      => 'images/reseps/pecel_lele.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 2,
                'title'          => 'Nasi Kuning',
                'description'    => 'Nasi kunyit gurih khas tumpeng.',
                'cook_duration'  => '00:40:00',
                'calorie'        => 510,
                'current_star'   => 4.7,
                'views_count'    => 190,
                'thumbnail'      => 'images/reseps/nasi_kuning.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 3,
                'title'          => 'Semur Daging',
                'description'    => 'Daging sapi empuk dengan bumbu kecap yang kaya rasa.',
                'cook_duration'  => '01:00:00',
                'calorie'        => 580,
                'current_star'   => 4.8,
                'views_count'    => 160,
                'thumbnail'      => 'images/reseps/semur_daging.webp',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
            [
                'user_id'        => 4,
                'title'          => 'Lodeh Sayur',
                'description'    => 'Sayuran dalam kuah santan yang gurih.',
                'cook_duration'  => '00:35:00',
                'calorie'        => 290,
                'current_star'   => 4.5,
                'views_count'    => 95,
                'thumbnail'      => 'images/reseps/sayur_lodeh.jpg',
                'main_filter_id' => 1,
                'is_published'   => true,
            ],
        ];

        foreach ($reseps as $resep) {
            Resep::updateOrCreate(
                ['title' => $resep['title']],
                $resep
            );
        }
    }
}